### ISSUE TITLE
[Bug] Sharing Button on ipad = always app crash

### ISSUE THREAD

**Issue by ChristianNoc** [BillGoldsmith/iOS-bugfest#168] opened 2023-05-21 12:39 UTC
## Brief description of the issue:
Sharing Button on ipad = always app crash

### Steps to reproduce:
Just hit the Sharing Button on iPad to crash the app ;-)

### Where did you see it? (App build version, device type and iOS version):
Build 0.9 (62), iPad mini 5, iOS iPadOS 16.4.1 (20E252) 

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0090](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/884d4c5c-0861-46b3-8f48-d0b135b063b6)

**Comment by bradtchapman** [comment] 2023-05-21 14:59
@ChristianNoc : bitte machen Sie die "Tastenformen" Bedienungshilfe kürzlich AUS, und die Textgrößekontrolle in der Mitte hingleiten, und die Sharing-taste wieder probieren.  Geht's ?


Bitte nehmen Sie ein Screenshot der Sharingfenster, privaten Detailen auslöschen, und das hier auf einen neuen Komment hinzufügen.  Soll es scrollen erfordern, um der ganze Fenster zu zeigen, dann teilen Sie bitte die 2 oder 3 Screenshots mit.  Danke im Voraus.

**Comment by ChristianNoc** [comment] 2023-05-21 15:48
Hello, oh you speak German or just with a translator?

ok I disabled the feature “Bedienhilfen/Tastenformen”. Now the buttons have text or icons, that looks nice now.

But the sharingbutton have the same behaviour. After tapping it, the app crashes immediately, meaning that I do not see the sharing Menue. I have to restart the app.

You are welcome :-)
CHRIStian. 

![IMG_0093](https://github.com/BillGoldsmith/iOS-bugfest/assets/134198993/10bc108d-6514-4059-983d-e9ed6ff4bac1)

**Comment by bradtchapman** [comment] 2023-05-21 16:05
@ChristianNoc : I speak German comfortably, with 3 years of classroom study plus some time as an exchange student.  The grammar and sentence structure might be slightly off in written form, but if you heard me speaking in conversation it would take much longer to uncover the ruse because I have no accent.  And I just got back from a vacation in Germany and Austria speaking German 99% of the time :-)

The crash must be caused by something configured in your share sheet, because the share button just generates a link and some text. 

Can you go to Safari, pick any website, tap the share button, and take screenshots with private details wiped out?

And what is your default app for web, mail, and messages?

**Comment by ChristianNoc** [comment] 2023-05-21 16:56
@bradtchapmanm : Oh ok. I try to speak English as much as possible… I hope that my English is at least understandable. Anyway it’s good to have German as an option ;-).

You are right the problem must be with the sharing configuration on my iPad. On the iPhone it works properly. I will need some time to do the screenshots…

**Comment by bradtchapman** [comment] 2023-05-22 12:46
@ChristianNoc - can you get the crash analytics and attach them here? 

You will need a computer to make a ZIP file because github doesn't allow uploading the .ips analytics generated by iOS.

1. Go to: Einstellungen > Datenschutz & Sicherheit > Analyse & Verbesserungen > Analysedaten ...
2. Drag finger down to reveal search bar.
3. Search for "Mk2"
4. Tap the newest file on the bottom of the list. 
5. Tap the Share button. 
6. Send to your computer by whatever means available.  
7. Compress the file to a .zip.
8. Upload here in a new comment.

**Comment by ChristianNoc** [comment] 2023-05-22 18:00
@bradtchapman : Good evening! Of course, here it comes…

Even when I am not a software engineer I thought that something with the sharing call must be a problem, because I have never experienced it with other apps. 

I send you the last 4 analyse files, in the newest I just opened the app and let it crash. So your developer should easily find what he need to find…

Just a information: FileBrowser pro https://www.stratospherix.com/products/filebrowserprofessional/
Can handle zip files on iOS. I love this Programm it’s really perfect file tool for iOS. For me a must have and really every penny worth…

[RadioParadiseMk2-2023-05-22-193829.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11534651/RadioParadiseMk2-2023-05-22-193829.zip)

One off topic question: I am new on GitHub and ask myself when should I use that @name function. I know when I mention a person in that way then he get informed but I guess all people that are assigned to that topic will be informed when I new comment comes in whether I use that @Name function, or not? And how is that @name function called in English and German?

**Comment by bradtchapman** [comment] 2023-05-22 18:29
@ChristianNoc : it's called "tagging."  The etymology and the idea comes from the children's playground game of **[Tag](https://en.wikipedia.org/wiki/Tag_\(game\))**, and in part the practice of applying labels or "tags" to objects for inventory.

Not everyone will be notified unless they enable notifications in GitHub.  People can choose to be notified with Github notifications, email, or both.  If they have the Github app installed, it probably fires notifications there.  I don't use it that much so I don't know.

**Comment by bradtchapman** [comment] 2023-05-22 18:30
@RPNate1 - crash logs submitted by user.

**Comment by ChristianNoc** [comment] 2023-05-22 18:44
> @ChristianNoc : it's called "tagging." The etymology and the idea comes from the children's playground game of **[Tag](https://en.wikipedia.org/wiki/Tag_(game))**, and in part the practice of applying labels or "tags" to objects for inventory.
> 
> Not everyone will be notified unless they enable notifications in GitHub. People can choose to be notified with Github notifications, email, or both. If they have the Github app installed, it probably fires notifications there. I don't use it that much so I don't know.

@bradtchapman : thanks 🙏 really cool explanation especially with the background, never have heard that before…

**Comment by RPNate1** [comment] 2023-05-22 18:59
Jarred is dialing in the share feature on the backend. This may be due to
whatever he is doing. We can check out the logs and see...

**Comment by donshefer** [comment] 2023-05-23 10:53
Crash was because of a missing view parameter on iPad.
Fixed in build 64

**Comment by ChristianNoc** [comment] 2023-05-25 07:31
@donshefer its working now on my iPad super. Shall I close that issue or do you that?

**Comment by bradtchapman** [comment] 2023-05-25 13:38
Closed, working per submitter.  Thanks for reporting.

**Closed as completed by bradtchapman** 2023-05-25 13:38 UTC
Labels: Bug P1 Critical, Device: iPad, Completed
