### ISSUE TITLE
[BUG] b62 Mac app hangs (beachball) if you attempt to navigate or scroll with arrow keys

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#141] opened 2023-05-19 17:27 UTC
## Brief description of the issue:
The Mac app (for Apple Silicon) will produce a spinning beachball (and sometimes a brief audio glitch) if you try to use the audio keys to navigate.  

### Steps to reproduce:
1. Launch app and start playing music.
2. Switch to info mode.
3. Click any element on the left or right column to put the cursor focus in this view.
4. Press any arrow key once.
5. The playback bar will disappear (unexpected) and the mouse cursor will go invisible (expected).
6. Move the mouse around to restore cursor visibility.
7. Now press the up, down, left, and right arrow keys **_randomly, in rapid succession_**.
8. In a few seconds, the app cursor will freeze and turn into a beachball while the music keeps playing.

### Expected result:
App should not freeze if user presses arrow keys.

### Actual result:
App freezes.

### Where did you see it? (App build version, device type and iOS version):
Build 62, 2021 MacBook Pro (M1 Pro), macOS 13.3.1.

*(Please provide screenshots or error message text when possible.)*

**Comment by bradtchapman** [comment] 2023-05-19 17:28
This should be tagged as major because it will completely kill app interaction and is unrecoverable.

I am generating a sysdiagnose to capture the app's current hang condition, if possible.

**Comment by bradtchapman** [comment] 2023-05-19 17:31
While sysdiagnose is being generated... here are the sample and spindump from Activity Monitor for the Radio Paradise app:

[RPMK2 B62 - Sample.txt.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11519146/RPMK2.B62.-.Sample.txt.zip)

[RPMK2 B62 - Spindump.txt.zip](https://github.com/BillGoldsmith/iOS-bugfest/files/11519147/RPMK2.B62.-.Spindump.txt.zip)

**Comment by bradtchapman** [comment] 2023-05-19 17:42
@RPNate1: see email for Dropbox link to Sysdiagnose file — I'm not going to post it on Github for privacy reasons.

**Comment by RPNate1** [comment] 2023-05-19 18:23
@donshefer I'll forward the sysdiagnose

**Comment by k00ka** [comment] 2023-05-19 20:30
Duplicate of #136?

**Comment by bradtchapman** [comment] 2023-05-19 20:43
@k00ka : it happens globally across the whole app, not just in comments.

**Comment by RPNate1** [comment] 2023-06-07 19:33
Still happening in b71

**Comment by RPNate1** [comment] 2023-06-13 16:56
I don't get the beachball anymore... but controls still disappear.

**Comment by k00ka** [comment] 2023-06-13 17:01
The specific instructions here don't work for me. But these do:
1. Launch app and start playing music.
2. Hamburger > Listen > Channels
3. Choose a different channel (back button appears)
4. Click back twice
5. Click an arrow key (controls disappear)

**Comment by RPNate1** [comment] 2023-06-13 17:19
Those didn't work for me. Controls stayed and no beach ball. 2021 16"
Macbook Pro Ventura 13.4

**Comment by k00ka** [comment] 2023-06-13 17:38
Interesting. I found that if I could get the back button to show (through whatever method, but generally by surfing secondary pages), then I could get it to happen. The 'keystroke rejected' sound would stop happening. On the next arrow key I'd be able to cause the controls to disappear.
Apple M1 Max
13.2.1 (22D68)

**Comment by donshefer** [comment] 2023-06-21 15:56
I believe this is working now. Please retest in build 80.

**Comment by RPNate1** [comment] 2023-06-21 17:55
fixed in b80

**Closed by RPNate1** 2023-06-21 17:55 UTC
Labels: Validate, Bug P2 High, Device: Mac, Issue: Confirmed, Issue: Planned
