### ISSUE TITLE
[Bug] My Favorites channel does not work

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#179] opened 2023-05-27 08:08 UTC
## Brief description of the issue:

Apparently the “my favorites” channel is not working properly for me. I have more than 100 songs rated accordingly, but there are quite a few songs that do not belong to my favorites or that I have not rated at all.
The expected favorites are not played ;-(

### Steps to reproduce:
Choose “my favorites” channel, check played songs
See screenshots
### Actual result:

“My favorites” channel plays any other stuff included songs I never have rated.

### Where did you see it? (App build version, device type and iOS version):
Build Mk2 09 (65), iPhone 12 Pro Max, iOS 16.5

*(Where possible, please attach Please provide screenshots or error message text)*

![IMG_0396](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/93aa67cc-3183-47f1-8999-fb8ae0354616)
![IMG_0397](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/8d8a3af5-33a9-4b4a-af2b-eb3548d41ca5)

**Comment by bradtchapman** [comment] 2023-05-28 02:41
@JoschiW64 : more information is required.  The developers will want to review your song listening and voting history.  To do this, they'll need your Radio Paradise User ID #.  Go to radioparadise.com in Safari, log in and access your user profile, then look at the end of the URL to get the number.

**Comment by JoschiW64** [comment] 2023-05-28 06:54
Hi, it’s 1016264615

I think I was just able to reproduce it: I started the app, then I selected the my fav channel. It actually started with a song I had rated. However, I did not want to listen to this one, but pressed the Next Track or Skip Forward "button". Then a track started that was not in my list. I was not able to get back to my favorites channel. Not even if I then selected any other channel and then selected the my favorites channel again. No chance!

Even "killing" the app (swipe away) and then restarting the app with the favorites channel did not lead to the fact that it continued with one of my favorites.

The expected behavior would be: that I can also jump forward WITHIN my favorites list while playing.
![IMG_0404](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/fe59f078-9ea7-458f-aac3-63ad9fa82af8)

I just noticed that my profile picture was not displayed on the screenshot. I am wondering why this is not the case. However, I checked and found that I was logged in. Then when I clicked on my profile picture in my profile, it was displayed. This did not change the behavior described regarding the Favorites Channel.

**Comment by bradtchapman** [comment] 2023-05-28 07:27
Just so you know... Radio Paradise does NOT allow you to go backwards to listen to earlier songs—even in your favorites playlist.  This is by design, and has never been implemented in any RP app, and likely never will.  

My best guess is that there is some legal requirement to prevent users going backwards to be considered an internet radio station, and not an on-demand streaming service.  It might change the licensing model and royalty payments, and therefore affect RP's operating costs.

**Comment by JoschiW64** [comment] 2023-05-28 08:27
Yes, sorry, that there was not and probably will not be the backward function, I also realized after writing my comment. But this is mainly about the forward function, which apparently kicks me out of the my favorites channel.,

--
Mit freundlichem Gruß / kind regards from Koblenz/Germany
Jochen
Am 28. Mai 2023, 09:27 +0200 schrieb bradtchapman ***@***.***>:

**Comment by JoschiW64** [comment] 2023-05-28 08:34
By the way, we have a couple of "public service" radio stations here called SWR1 and SWR3. Both have an app within which you can skip back and forward a few hours. You can also save favorites and click on one at any time and play it immediately.

--
Mit freundlichem Gruß
Jochen Weber
Am 28. Mai 2023, 09:27 +0200 schrieb bradtchapman ***@***.***>:

**Comment by RPNate1** [comment] 2023-05-28 20:13
Rewinding isn't possible due to our licensing agreements.
I'll explore this bug further on Tuesday when I return to work (Monday is
US holiday).

**Comment by RPNate1** [comment] 2023-05-28 20:20
Go ahead and uninstall the app and reinstall. I looked at your ratings and didn't see those songs. Let me know if it persists after reinstalling.

**Comment by JoschiW64** [comment] 2023-05-28 20:59
Uninstalled, reinstalled, issue still persists.
![Uploading IMG_0437.png…]()

**Comment by JoschiW64** [comment] 2023-05-28 21:06
Uninstalled, reinstalled, issue still persists.

Kind regards
Jochen
Am 28. Mai 2023, 22:20 +0200 schrieb RPNate1 ***@***.***>:

**Comment by JoschiW64** [comment] 2023-05-29 06:49
![IMG_0436](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/5a5ecaf0-96f8-490e-abc9-fc95479abdfa)

**Comment by JoschiW64** [comment] 2023-05-30 07:04
This for your information: the described behavior also occurs when I do not "skip" but simply let the channel run. Then usually the first title is indeed a favorite - and everything that comes after that is pure coincidence and does not correspond to my favorite selection.

**Comment by RPNate1** [comment] 2023-05-30 18:32
I confirmed these tracks aren't in your rated songs. Not sure what's happening here. 
@donshefer what do we need to do to diagnose this issue? 
@jarro any ideas what's going on?

**Comment by RPNate1** [comment] 2023-05-30 18:59
Confrimed that the favorites is playing random unrated songs for me, as well. First song is in my favorites, everything that follows is not.

**Comment by jarro** [comment] 2023-05-30 19:38
can reproduce this.  will get that sorted out.

**Comment by jarro** [comment] 2023-05-30 20:46
this should be fixed

**Comment by JoschiW64** [comment] 2023-05-30 20:53
Thanks a lot.

**Comment by bradtchapman** [comment] 2023-05-30 21:06
Seems to be working; I loaded my favorites and got nothing but 7's, 8's, 9's and 10's.

**Comment by RPNate1** [comment] 2023-05-30 21:23
Confirmed fixed in b65

**Closed as completed by RPNate1** 2023-05-30 21:23 UTC
Labels: Bug P2 High, Issue: Confirmed

**Comment by JoschiW64** [comment] 2023-05-30 21:51
I am happy to confirm that as well. Thank you for your efforts and quick help!

**Comment by JoschiW64** [comment] 2023-06-05 17:13
After restarting necessary due to a crash, again I had a song in my favorites channel not being one of my favs:
![IMG_0608](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/be9b1bfb-d788-4db9-98b1-9ae06be32ad8)
