### ISSUE TITLE
[Bug] Swipe right gesture results in a blank white screen, if autostart on launch is disabled.

### ISSUE THREAD

**Issue by bradtchapman** [BillGoldsmith/iOS-bugfest#194] opened 2023-06-01 21:50 UTC
## Brief description of the issue:
I got a blank white screen when I swiped right after launching the app.  I have autostart disabled.  

### Steps to reproduce:
1. Disable Autostart.
2. Kill the app from the iOS task switcher (note: this will be the default state after a recent update). 
3. Launch the app.
4. Swipe left-to-right.
5. The screen turns white.

### Expected result:
I'm not sure what I expected...

### Actual result:
I should have been able to back out or swipe back to the main window.  I had to kill the app.

### Where did you see it? (App build version, device type and iOS version):
Build 68, iOS 16.4, iPhone 12 Pro.

*(Where possible, please attach Please provide screenshots or error message text)*

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/36425ae1-a4f4-4b85-aa42-5be79f70a17a

**Comment by RPNate1** [comment] 2023-06-01 23:01
can't reproduce.

**Comment by bradtchapman** [comment] 2023-06-02 02:38
I can, and on the iPad to boot!

Make sure you see the RP logo.  If a song has already started and you pause it, the bug won't occur.  

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/e59b0baf-7193-4f45-af0c-7e355fc1e039

**Comment by bradtchapman** [comment] 2023-06-02 05:40
Reproduced on the tiny phone running build 68 and iOS 15.7.3.  The screen turns black instead of white, but I suspect the underlying behavior is the same. 

In this video, you'll see what happens when you swipe left, down, and right.  All while no music has yet loaded.  

https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/02e2465b-f905-434a-8964-77776f7dc112

**Comment by donshefer** [comment] 2023-06-02 09:19
Slideshow is only available when a song is loaded which happens when a channel is played.
Swipe right will be ignored if there is no song to show.
Fixed in build 69

**Comment by ChristianNoc** [comment] 2023-06-06 02:32
@donshefer 

Can confirm that it is fixed
Build 0.9 (70), iPad mini 5, iOS iPadOS 16.5

**Closed as completed** 2023-06-06 17:44 UTC
Labels: New Issue, Validate, Bug P2 High

**Comment by bradtchapman** [comment] 2023-06-06 23:54
Confirmed fixed.  Using build 71 now.  Thanks!
