### ISSUE TITLE
[Bug] App crashes on Send Feedback

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#273] opened 2023-08-03 17:21 UTC
## Brief description of the issue:
Selecting "send feedback" from Settings causes the app to crash

### Steps to reproduce:
1. profile menu > settings > send feedback

### Expected result:
I was trying to send feedback on another issue.

### Actual result:
The app crashes.

### Where did you see it? (App build version, device type and iOS version):
Version 8.0.0, Build 1003, Macbook Pro M1 Max, Ventura 13.4 (22F66)

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by bradtchapman** [comment] 2023-08-03 19:23
Unable to reproduce this on my end in Build 1003 from iPhone.  Is this happening on the Mac? Did you try the iPhone?

Edit: **CONFIRMED on Mac**.  Near-instant crash when clicking "Send Feedback."

**Comment by k00ka** [comment] 2023-08-03 19:30
Brad,

I will try the iPhone….. (tries the iphone)….. It works there. Perhaps the issue has to do with iOS native interactions to create this popup:

￼

Feel free to close this one. It only hamstrings me from prepping reports on the laptop.

FYI I did confirm that the other bug exists on the iPhone.


David
 
RYATTAGROUP   |   DELIVERING BETTER SOFTWARE   |   +1-416-998-1234   |   http://www.ryatta.com <http://www.ryatta.com/?source=email>   |    @ryattagroup <http://twitter.com/ryattagroup>

This email message, and any attachments, is intended only for the named recipient(s) above and may contain content that is privileged, confidential and/or exempt from disclosure under applicable law. If you have received this message in error, please notify the sender and delete this email message. Thank you.

**Comment by RPNate1** [comment] 2023-08-03 23:26
I don't even have the option of sending feedback on my Mac version. ??
<img width="256" alt="Screenshot 2023-08-03 at 4 25 27 PM" src="https://github.com/BillGoldsmith/iOS-bugfest/assets/123519331/fc66a078-8de6-495b-a058-9f43afb79299">

**Comment by RPNate1** [comment] 2023-08-04 17:26
I've had a few more reports of this. Gonna need to sort this out.

**Comment by k00ka** [comment] 2023-08-04 17:42
> I don't even have the option of sending feedback on my Mac version. ??
> <img alt="Screenshot 2023-08-03 at 4 25 27 PM" width="256" src="https://user-images.githubusercontent.com/123519331/258257945-fc66a078-8de6-495b-a058-9f43afb79299.png">

That is, indeed, strange. Like it's hidden somehow?

**Comment by donshefer** [comment] 2023-08-08 12:15
The "Send Feedback" button only shows if you have an email account set up in the OS.
We are discussing options for this.

**Comment by donshefer** [comment] 2023-08-10 08:34
Fixed crash in macOS in build 1005
Also added messaging when email is not available

**Comment by ChristianNoc** [comment] 2023-08-10 14:00
Fixed for iPad mini 5 in build 1005. It’s ok now…

**Comment by RPNate1** [comment] 2023-08-10 20:16
fixed in b1005 
the error message works. Thanks!

**Closed as completed by RPNate1** 2023-08-10 20:16 UTC
Labels: Bug P1 Critical, Validate, Device: Mac, Issue: Confirmed, Feature: Settings
