### ISSUE TITLE
[BUG] Disappearing song controls

### ISSUE THREAD

**Issue by k00ka** [BillGoldsmith/iOS-bugfest#138] opened 2023-05-19 02:50 UTC
## Brief description of the issue: 
The song controls disappear when focus is on a song and command key is pressed

### Steps to reproduce: 

1. Play a stream 
2. Click on the song list (three lines in controls) 
3. Click in the current song (works both if you click on words and then click back or click on the non-text area of the song) 
4. Press control key 
5. Song controls disappear

### Expected result: 
The song controls should be unaffected

### Actual result: 
The song controls disappear

### Where did you see it? (App build version, device type and iOS version): 
Mk2 Version 0.9 Build 61

*(Please provide screenshots or error message text when possible.)*
![Screenshot 2023-05-18 at 10 46 36 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/6089c9d9-1f28-4865-8924-efc6a118b6d9)
![Screenshot 2023-05-18 at 10 50 15 PM](https://github.com/BillGoldsmith/iOS-bugfest/assets/791371/478d5a29-3d40-4a8a-b530-e41720089b12)

**Comment by RPNate1** [comment] 2023-05-19 16:41
That's weird. I was able to replicate this. Great catch, @k00ka

**Comment by bradtchapman** [comment] 2023-05-19 16:47
@RPNate1 : Reproduced, with more detail: pressing **ANY KEY** on this screen will cause the controls to disappear.

**Comment by RPNate1** [comment] 2023-05-22 23:44
Keyboard controls are being updated.

**Comment by RPNate1** [comment] 2023-06-07 19:31
I tried this one and got the beachball of death today. After the controls disappeared.

**Comment by RPNate1** [comment] 2023-06-13 16:53
Still happening.

**Comment by donshefer** [comment] 2023-06-21 16:04
@RPNate1 It's not a bug, its a feature. :) The controls are hidden when the keyboard is displayed. But, it should only happen on iPhone, not iPad or Mac. Fixed.
Updated in build 80.

**Comment by RPNate1** [comment] 2023-06-21 17:53
fixed in b80

**Closed by RPNate1** 2023-06-21 17:53 UTC
Labels: Validate, Bug P2 High, Device: Mac, Issue: Confirmed, Issue: Planned
