### ISSUE TITLE
Download blocks disappearing.

### ISSUE THREAD

**Issue by jarro** [BillGoldsmith/iOS-bugfest#295] opened 2023-09-06 08:03 UTC
Getting a few complaints like this,  but can't reproduce it.  I'll just collect them here to look for a pattern.

**Comment by jarro** [comment] 2023-09-06 08:03
The day your updated ios app debuted my cache disappeared. Thought this was maybe a one-off, but no, each day is like Groundhog Day. This is happening with my wife's phone as well. Not going to be too convenient on upcoming travels.

**Comment by jarro** [comment] 2023-09-06 08:08
Greetings from sunny Málaga in Southern Spain. Thanks ever so much for your fantastic radio station, an ever-present companion for more than 15 years now.

I want to report that the new version of the app doesn't work well with downloaded blocks; they just disappear after a little while. I hope a bug fix is on the way because it is such a  fantastic feature especially for FLAC...

Anyway, thanks in advance for your help!

**Comment by donshefer** [comment] 2023-09-06 14:06
@jarro I am looking into this also, but I have not been able to reproduce it yet.

**Comment by jarro** [comment] 2023-09-07 10:38
@donshefer    Only thing that comes to mind is if it's using a cache folder the os may wipe it to create space.  Something I ran into on Android.

**Comment by jarro** [comment] 2023-09-07 10:39
New App not working on IPhone 14
The download is not working since the app was changed. I can download music but when I go to playback it just goes to pause.  When I go back to the download manager the downloaded music has disappeared. I have tried med and high bit rate but no luck on either. I can live stream but I listen in my car a lot and use the download all of the time.

**Comment by jarro** [comment] 2023-09-07 10:54
On the support front, this has been an ongoing issue and still is in the new iOS version 8.0.0(1014).  Started playing the live stream, and downloaded the next two hours.  Went for a run and consumed 45 min of 120.  Stopped playing and went to work.  Got in the car, with no WiFi, and want to continue playing where I left off from the 75 minutes that should have remained in the earlier cache of live stream.  Nada.  The following message, and dead in the water, cache dumped.    ( the screenshot is just him trying to play main mix with the no network error )

**Comment by jarro** [comment] 2023-09-07 21:46
I'm enjoying the new functionality of the new iOS app - great bonus to have FLAC now. Thanks!

However.....I'm experiencing an issue with the cache facility - it keeps evaporating for no reason.  In detail, my daily commute includes around an hour each way via subway - no wifi or cellular data available.  I've always downloaded a few hours into the cache for playback whilst I'm without any signal.  But. with the new app on day one, I downloaded around three hours only to find that it refused to play within half an hour of being without signal - an error message told me I needed a connection to play the stream.  I subsequently found there was around two hours plus still in the cache, so I topped it up again for day two.  Now I had around six hours in the cache but, once again, the app stopped playing within half an hour of being without a connection.  Subsequently, I found the whole cache had been lost.  Today, day three, I downloaded a couple of hours to play through my car system, but the cache stopped playing and seemed to have been wiped within half an hour.  Am I missing something with the new functionality - perhaps with the new 'Pre-Load Facility'? 

Apologies if this is a known issue - I couldn't spot a previous reference to the same problem.

**Comment by donshefer** [comment] 2023-09-08 06:19
https://github.com/BillGoldsmith/iOS-bugfest/issues/295#issuecomment-1709941026
This one actually makes sense. Sounds like he was using the preload cache and it timed out. Perhaps we should communicate that there is a timeout period for the preload cache.

https://github.com/BillGoldsmith/iOS-bugfest/issues/295#issuecomment-1710807817
This one also, sounds like they might get hitting the preload timeout.

It would be great to get logs. It is not clear whether these people are using the preload cache or the downloaded blocks.

Still investigating...

**Comment by jarro** [comment] 2023-09-08 10:52
My downloads play for two or three songs and then self-delete. This has happened nearly every time I have created a download. I had four downloads just disappear despite  their being listed each with 3 plus hours of music, as was the case in the previous version of your app. 
I down load the full time amount per selection at the FLAC level most of the time.

**Comment by jarro** [comment] 2023-09-08 11:38
@donshefer    if preload has a timeout that's not clear from the description. But the disappearing issue might affect both preloads and downloads.

On the block deletion front found one way to reproduce this fairly quickly.

With empty downloads  download 10 minutes.
Start listening when download finishes.
While listening download a few hours.  
Music will stop after a few songs and downloads will usually be empty.

Also unrelated,  but if you delete a downloading block it keeps downloading.

**Comment by donshefer** [comment] 2023-09-08 12:02
Ok, I will give that a try.

You are downloading more into the block that is playing?

**Comment by donshefer** [comment] 2023-09-08 14:20
@jarro OK, found the issue. It was a bug in the cached song player code.
It was being triggered when additional songs were added to a currently playing cache. It was removing the cache, not realizing there were more songs available.
Rolling up a fix build now.

I am also making a note to make the in-progress downloads cancelable.

**Comment by donshefer** [comment] 2023-09-08 15:29
Fixed in version 8.0.1 build 1017.

**Comment by RPNate1** [comment] 2023-09-15 20:13
Let's give this fix some good testing team. This is the biggest bug since launch.

**Comment by ChristianNoc** [comment] 2023-09-21 07:54
@RPNate1 @donshefer 

**Some test results: iphone11 Pro - 16.6.1. - 8.1.0(1021)**
**I have tested the download function in several ways, especially weird scenarios like:**
• quitting the app with task killer during the download (at least more than 3 times for each download).
•  reopening the app and switching channels in crazy ways, especially switching between other downloaded blocks
• Switching the connection from WiFi to mobile and vice versa.
• leaving the app in the background and doing other things (not listening)
• Doing things that a user with at least a little technical background would not do.

**Result:**
Once an error message appears. Unfortunately only the red error message "Download failed" and no further information. Nevertheless it looks like the last active download is queued, because after a short time the download starts again where it was stopped by the error. For me, the download function works very solid, even if you do crazy things.

**What is for me not consistent is the status "turning wheel" under the play/pause sign. Obviously an active block download does not show that "turning wheel". And technical that is not a fine solution. Either data traffic is attracted or not. A bit sometimes and sometimes  a bit not makes absolutely no sense and is in this way a useless information. Then its better to have not a little bit data transfer signal at all. :-).** 

**What I have not tested yet:**
I have not yet tested the "auto-refill" function in the same way, nor the adding blocks function (i.e. a second download is added to an existing one). My focus was "only" on the download function for new downloads.

**Comment by RPNate1** [comment] 2023-10-02 19:17
fixed in the 8.1 update

**Closed as completed by RPNate1** 2023-10-02 19:17 UTC
Labels: Validate
