### ISSUE TITLE
[BUG] b62: Download Manager offers 40 songs but loads max 31

### ISSUE THREAD

**Issue by jadRafay** [BillGoldsmith/iOS-bugfest#150] opened 2023-05-20 02:17 UTC
## Brief description of the issue:

DM used to allow creation of very large blocks -- handy for long plane trips.

### Steps to reproduce:

Open DM, select a bit rate and say "40 songs".

### Expected result:

40 songs!  :-)

### Actual result:

DM top line says "Downloading x% of 31 songs".
Only 31 songs are loaded in the cache block.
Until the load finishes the block says "40 songs requested, 0 in cache".

When I request another of the same channel and bitrate I can get additional
songs to load, and even go over 40 songs total.  But I can't keep going...

### Where did you see it? (App build version, device type and iOS version):

RP Mk2, build 62, iPhone Xs running iOS 16.2

**Comment by bradtchapman** [comment] 2023-05-20 04:21
Duplicate of #123, which will be reopened.

**Closed by bradtchapman** 2023-05-20 04:21 UTC
Labels: New Issue, Closed: Duplicate

**Comment by JohnADilley** [comment] 2023-05-22 13:57
Confirmed this is fixed in b63 (issue #123 can be closed?)

**Comment by bradtchapman** [comment] 2023-05-22 14:55
@JohnADilley : nope...

![IMG_4453](https://github.com/BillGoldsmith/iOS-bugfest/assets/32527656/e234dd2d-3195-46e9-93ff-4595cf39f537)
