### ISSUE TITLE
[Bug] Broken links to “Artist Website” and “(more from Wikipedia)” 

### ISSUE THREAD

**Issue by JoschiW64** [BillGoldsmith/iOS-bugfest#181] opened 2023-05-29 09:50 UTC
## Brief description of the issue:
Blue links in artist’s info section don’t lead to corresponding 
![IMG_0440](https://github.com/BillGoldsmith/iOS-bugfest/assets/134329308/fe646cae-f453-4e50-88b7-e72a27995c08)
info pages

### Steps to reproduce:

Click on "more info..." in the info area for a title.
At the end of the artist or band info click on one of the two blue links "Artist website" or "(more from Wikipedia)".

### Expected result:

Corresponding web page with info about artist or band should open.

### Actual result:
Corresponding pages don’t appear/don’t open. 

### Where did you see it? (App build version, device type and iOS version):

Build Mk2 0.9 (65), iOS 16.5, iPadOS 16.6

This happens regardless of which band or artist I tried this with, and it happens just as much on my iPhone 12 Pro Max as it does on my 5th generation iPad Air

*(Where possible, please attach Please provide screenshots or error message text)*

**Comment by RPNate1** [comment] 2023-05-30 17:08
Confirmed.

**Comment by RPNate1** [comment] 2023-05-30 19:04
@jarro is this you since it's web views?

**Comment by jarro** [comment] 2023-05-30 19:33
These would need to launch an external browser.    Ideally best if detected and intercepted by the  app.   As there will be similar links scattered around  in song comments and blog posts.

**Comment by RPNate1** [comment] 2023-06-06 19:43
@donshefer did you see @jarro 's response to this?

**Comment by donshefer** [comment] 2023-06-20 15:50
fixed in build 79

**Comment by RPNate1** [comment] 2023-06-20 23:47
fixed b79

**Closed as completed by RPNate1** 2023-06-20 23:47 UTC
Labels: Validate, Bug P2 High, Device: iPhone, Device: iPad, Issue: Confirmed
